highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://lopof.github.io
author: Thomas Baumann 

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /
title: Thomas Baumann Vitae
name: Thomas Baumann  
email: thbaumann90@gmail.com
email_full: mailto:thbaumann90@gmail.com
website: github.com/lopof
website_full: https://github.com/lopof
github: lopof
twitter: 
tel: 
tel_full: 
google_maps: ''
address:
  street: 
  postcode: 
  city: 
  country: 
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
